apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: getting-started
          image: santospardos/unir:getting-started
          ports:
            - containerPort: 3000
