apiVersion: v1
kind: Service
metadata:
  name: gettingstarted-svc
  labels:
    env: dev
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    env: dev
